# Generated by Django 4.2.16 on 2024-12-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitdate', models.IntegerField(default=0)),
                ('visitlocation', models.IntegerField(default=0)),
            ],
        ),
    ]
