# Generated by Django 4.2.16 on 2024-12-11 06:20

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="전화번호는 '000-0000-0000' 형식으로 입력해주세요.", regex='^\\d{3}-\\d{3,4}-\\d{4}$')], verbose_name='연락처')),
                ('preferred_date', models.DateField(default=django.utils.timezone.now, help_text='방문을 원하시는 날짜를 선택해주세요', verbose_name='방문 희망 날짜')),
                ('preferred_time', models.CharField(choices=[('morning', '오전 (09:00-12:00)'), ('afternoon', '오후 (12:00-17:00)'), ('evening', '저녁 (17:00-19:00)')], help_text='원하시는 방문 시간대를 선택해주세요', max_length=20, verbose_name='선호 방문 시간대')),
                ('available_location', models.CharField(max_length=200, verbose_name='방문 가능 지역')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일시')),
            ],
            options={
                'verbose_name': '상담 신청',
                'verbose_name_plural': '상담 신청 목록',
            },
        ),
    ]
